### ISSUE TITLE
Add mobile responsiveness to the site. (High Priority)

### ISSUE THREAD

**Issue by adelicia-js** [Shanki200801/LoyolaWebsite#52]
*Self-explanatory* :)

**Comment by Shanki200801** [comment]
we need to discuss this. do we make nav bar hamburger menus?

**Comment by programmingMohit** [comment]
> we need to discuss this. do we make nav bar hamburger menus?

I think yea best to make them hamburger menu

**Comment by adelicia-js** [comment]
> we need to discuss this. do we make nav bar hamburger menus?

Verily, a discussion of great importance dost arise - the matter of crafting a navigation bar adorned with the revered hamburger menu. In truth, the decision to adopt such a design element doth bear weight upon the minds of many a web designer and developer. The hamburger menu, like a soliloquy delivered upon a grand stage, hath its merits and limitations. In the realm of web design, the true wisdom lieth in the understanding that no single approach doth fit all scenarios.

**Comment by Shanki200801** [comment]
Checklist for pages to be made responsive apart from home page:

- [x] about college
- [x] vision mission
- [x] crest and anthem
- [ ] core values
- [x] management
- [ ] academics/ba
- [ ] academics/bcom
- [ ] academics/certificatecourses
- [ ] results
- [x] facilities/sports
- [x] facilities/libraries
- [x] facilities/sports
- [x] news and events
- [ ] student/associations
- [ ] student/placements
- [ ] student/grievances
- [x] student/council
- [x] student/student-achievements
- [ ] departments
- [ ] admission index page
