### ISSUE TITLE
Additional content to be put up

### ISSUE THREAD

**Issue by Shanki200801** [Shanki200801/LoyolaWebsite#57]
## About
1. founder
2. History
3. Management (remove from dept and add new page)

## Potential newpages linked via nav or support and assistance icons on home page
1. student achievements
2.  staff achievements
3. anti ragging cell
4. counselling
5. library *
6. content in results page
7. sports?

**Comment by adelicia-js** [comment]
- I've pushed a new page 'About University' to my branch '51-about-overhaul'. That contains content for 'Founder' & 'History'.
- I will create a new page called 'Infrastructure' and it will contain 'Library', 'Sports' and other list items from the old website.

**Comment by Shanki200801** [comment]
>     * I will create a new page called 'Infrastructure' and it will contain 'Library', 'Sports' and other list items from the old website.
 there is already a infrastructure.js page with all the items present in their old site. Need to make a separate section for sports and library cause there is a lot more content to put up for those two in praticular

**Comment by adelicia-js** [comment]
> > ```
> > * I will create a new page called 'Infrastructure' and it will contain 'Library', 'Sports' and other list items from the old website.
> > ```
> 
> there is already a infrastructure.js page with all the items present in their old site. Need to make a separate section for sports and library cause there is a lot more content to put up for those two in particular

Ah, I see. Cool, will make separate pages for them.

**Comment by Shanki200801** [comment]
All content present here is added! Closing issue
